project_name: Plywood Gallery
repository_url: https://github.com/kolibril13/plywood-gallery
user_content_version: 0.15.1
description: |
  Normal cells are independent of each other, and can be run togehter with the "Header" cell. <br>
  A "Dependent" cell depends on the "Normal" cell left to it. <br>
  A "Dependent" cell depends on another "Dependent" cell left to it.
favicon: favicon.ico
custom_footer: |
  <div style="position: fixed; bottom: 10px; right:10px"> <a href="code_animation_idea.html">
  Link to code animating idea!</a></div>
gallary_parameters_path: gallery_assets/gallery_parameters.json
